---
- hosts: all
  gather_facts: false
  tasks:
    - name:  wait for SSH to come up
      wait_for_connection: 
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user
 #la parte de arriba es una prueba para ver si se espera
 #al ssh para conectar para que no pete.
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: Start Apache service
      service:
        name: httpd
        state: started
    - name: Restart Apache service
      service:
        name: httpd
        state: restarted
    - name: Copy local directory to remote server
      copy:
        src: "../hello-2048/public_html/"
        dest: "/var/www/html/"
        owner: apache
        group: apache
        mode: 0755
